### ISSUE TITLE
Trouble running program when not in debugger

### ISSUE THREAD

**Issue by gbriggs-trmb** [WaveEngine/Feedback#100]
I have built your Automotive sample. I have no trouble running the program when I launch it from the debugger. 

When I try to launch the program without the debugger attached, it works about 1/100 times, but it usually crashes just after loading the steering wheel / car icons, but before the graphics engine shows anything on the window.

I have tried debug and release, and I created x64 configurations and tried those as well. All are consistent, work when launched under debugger, but crash almost every time when running without the debugger.

I checked the event viewer, and I copied the interesting part at end of this report. There is something in there about adding same key to dictionary twice.

For what it worth, the key "d743adde-eb54-4f0b-8bc3-e431a34f762d" appears in the solution here:

`  /// <summary> Asset Path (Computes/PostProcessing/Histogram.wefx) </summary>
                public static readonly Guid Histogram = new Guid("d743adde-eb54-4f0b-8bc3-e431a34f762d");
                `

Any help is appreciated.  Thank you

Event Viewer Log:
================

 `Application: AutomotiveDemo.WPF.exe
CoreCLR Version: 5.0.1121.47308
.NET Version: 5.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: An item with the same key has already been added. Key: d743adde-eb54-4f0b-8bc3-e431a34f762d.wepfx
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at WaveEngine.Framework.Services.AssetsService.Load[T](String path, Boolean forceNewInstance)
   at WaveEngine.Framework.Services.AssetsService.Load[T](Guid id, Boolean forceNewInstance)
   at WaveEngine.Framework.Graphics.AutoExposure..ctor()
   at WaveEngine.Framework.Graphics.CameraDrawContext.ProcessAutoExposure()
   at WaveEngine.Framework.Graphics.CameraDrawContext.Render(CommandBuffer commandBuffer)
   at WaveEngine.Framework.Graphics.DefaultRenderPipeline.RenderSingleCamera(CameraDrawContext cameraContext)
   at WaveEngine.Framework.Graphics.DefaultRenderPipeline.Render(TimeSpan gameTime)
   at WaveEngine.Framework.Managers.RenderManager.Draw(TimeSpan gameTime)
   at WaveEngine.Framework.Managers.SceneManagers.DrawSceneManagers(TimeSpan gameTime)
   at WaveEngine.Framework.Scene.Draw(TimeSpan gameTime)
   at WaveEngine.Framework.Scene.BaseDraw(TimeSpan gameTime)
   at WaveEngine.Framework.ScreenContext.Draw(TimeSpan gameTime)
   at WaveEngine.Framework.Services.ScreenContextManager.Draw(TimeSpan gameTime)
   at WaveEngine.Framework.Application.DrawFrame(TimeSpan gameTime)
   at AutomotiveDemo.WPF.App.<>c__DisplayClass4_0.<OnStartup>b__1()
   at WaveEngine.WPF.WPFWindowsSystem.CompositionTarget_Rendering(Object sender, EventArgs e)
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
`

**Comment by jcant0n** [comment]
Thank you for taking the time to report this issue. We are closing it due to extended inactivity. If you believe this issue is still relevant, please feel free to reopen it and we will be happy to revisit it. Thank you for your understanding and for helping us improve Evergine.
