### ISSUE TITLE
Shadow?

### ISSUE THREAD

**Issue by Hromon** [WaveEngine/Feedback#33]
Does WaveEngine have shadow support from the box? О.о

And is there an approximate release date for 3.0?

Thanks.

**Comment by jcant0n** [comment]
Hi Hromon,

We are working on a new Dynamic Shadow System for WaveEngine 3.2 preview to support all our lights types: Spot, Directional, Point and Area lights.

We have spent the last year rewriting the entire engine and before dynamic shadows we had a lot of things to do, so now only static shadows (lightmaps) are supported officially from the box. 

But we understand this as the next most important thing we have to do for this new code base.

Thanks for your feedback.

**Comment by Hromon** [comment]
Thanks from ansfer.

I love the architecture of your engine and am eager to know when there will be a stable 3.0 release?

**Comment by jcant0n** [comment]
From today you can download the WaveEngine 3.1 version with .NET 5 and C# 9 support. And try all the new samples based on this version from: https://github.com/WaveEngine/Samples.

Hope you like it!

**Comment by Hromon** [comment]
![image](https://user-images.githubusercontent.com/29508584/104358248-38c95d80-551f-11eb-8b9c-00c3b02e6a1b.png)
![image](https://user-images.githubusercontent.com/29508584/104358281-45e64c80-551f-11eb-84b3-cb91e5c2723a.png)

о/
if true then no crash

**Comment by Hromon** [comment]
Error if i enable shadow:

Exception sending view command '"UpdateContainerRequest"' for view: "7a0113d2-55e4-4f5f-8b5e-14bc40210309"
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at WaveEngine.Framework.Graphics.DefaultRenderPipeline.CreateLightDrawContext(Light light) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\Default\DefaultRenderPipeline.cs:line 200
   at WaveEngine.Framework.Graphics.DefaultRenderPipeline.Light_OnShadowEnabledChanged(Object sender, Boolean shadowEnabled) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\Default\DefaultRenderPipeline.cs:line 220
   at WaveEngine.Framework.Graphics.Light.FireOnShadowEnabledChanged() in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\Lighting\Light.cs:line 221
   at WaveEngine.Framework.Graphics.Light.set_IsShadowEnabled(Boolean value) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\Lighting\Light.cs:line 75
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at System.Reflection.PropertyInfo.SetValue(Object obj, Object value)
   at WaveEngine.Editor.Extension.PropertyEditor`1.SetMemberValue(TPropertyType value) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Editor.Extension\PropertyEditor`1.cs:line 82
   at WaveEngine.Runner.PropertyPanel.PropertyInfo`2.UpdatePropertyValue(PropertyData newPropertyData) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\PropertyPanel\PropertyInfo`2.cs:line 52
   at WaveEngine.Runner.PropertyPanel.PanelPropertyContainer.UpdateProperty(PropertyData propertyData) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\PropertyPanel\PanelPropertyContainer.cs:line 119
   at WaveEngine.Runner.PropertyPanel.PanelContainer`1.UpdatedContainer(Container container) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\PropertyPanel\PanelContainer`1.cs:line 234
   at WaveEngine.Runner.PropertyPanel.PanelContainer`1.UpdatedContainer(Container container) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\PropertyPanel\PanelContainer`1.cs:line 218
   at WaveEngine.Runner.PropertyPanel.PanelContainer`1.UpdatedContainer(Container container) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\PropertyPanel\PanelContainer`1.cs:line 218
   at WaveEngine.Runner.Viewers.BaseEditorScene.UpdateProperty(Container container) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\Viewers\BaseEditorScene.cs:line 101
   at WaveEngine.Runner.Services.Commands.UpdateContainerHandler.ExecuteAsync(ICommandHandlerResult result, Boolean isRedo) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\Services\Commands\UpdateContainerHandler.cs:line 26
   at WaveEngine.Runner.Services.UndoRedoService.Do(ICommandHandler handler, BaseEditorScene linkedScene) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\Services\UndoRedoService.cs:line 82
   at WaveEngine.Runner.Services.Server.ViewCommandsService.BaseExecuteCommand(Command command, Object parameter, BaseEditorScene linkedScene) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\Services\Server\ViewCommandsService.cs:line 119
   at WaveEngine.Runner.Services.Server.ViewsEditorServer.SendViewCommand(IAsyncStreamReader`1 requestStream, ServerCallContext context) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\Services\Server\ViewsEditorServer.cs:line 267
