### ISSUE TITLE
Shadow bug

### ISSUE THREAD

**Issue by Hromon** [WaveEngine/Feedback#51]
Error if i enable shadow:

Exception sending view command '"UpdateContainerRequest"' for view: "7a0113d2-55e4-4f5f-8b5e-14bc40210309"
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.NullReferenceException: Object reference not set to an instance of an object.
at WaveEngine.Framework.Graphics.DefaultRenderPipeline.CreateLightDrawContext(Light light) in C:\agent_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\Default\DefaultRenderPipeline.cs:line 200
at WaveEngine.Framework.Graphics.DefaultRenderPipeline.Light_OnShadowEnabledChanged(Object sender, Boolean shadowEnabled) in C:\agent_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\RenderPipeline\Default\DefaultRenderPipeline.cs:line 220
at WaveEngine.Framework.Graphics.Light.FireOnShadowEnabledChanged() in C:\agent_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\Lighting\Light.cs:line 221
at WaveEngine.Framework.Graphics.Light.set_IsShadowEnabled(Boolean value) in C:\agent_work\5\s\src\Engine\Common\WaveEngine.Framework\Graphics\Lighting\Light.cs:line 75
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
at System.Reflection.PropertyInfo.SetValue(Object obj, Object value)
at WaveEngine.Editor.Extension.PropertyEditor1.SetMemberValue(TPropertyType value) in C:\agent\_work\5\s\src\Engine\Common\WaveEngine.Editor.Extension\PropertyEditor1.cs:line 82
at WaveEngine.Runner.PropertyPanel.PropertyInfo2.UpdatePropertyValue(PropertyData newPropertyData) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\PropertyPanel\PropertyInfo2.cs:line 52
at WaveEngine.Runner.PropertyPanel.PanelPropertyContainer.UpdateProperty(PropertyData propertyData) in C:\agent_work\5\s\src\Tools\Editor\WaveEngine.Runner\PropertyPanel\PanelPropertyContainer.cs:line 119
at WaveEngine.Runner.PropertyPanel.PanelContainer1.UpdatedContainer(Container container) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\PropertyPanel\PanelContainer1.cs:line 234
at WaveEngine.Runner.PropertyPanel.PanelContainer1.UpdatedContainer(Container container) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\PropertyPanel\PanelContainer1.cs:line 218
at WaveEngine.Runner.PropertyPanel.PanelContainer1.UpdatedContainer(Container container) in C:\agent\_work\5\s\src\Tools\Editor\WaveEngine.Runner\PropertyPanel\PanelContainer1.cs:line 218
at WaveEngine.Runner.Viewers.BaseEditorScene.UpdateProperty(Container container) in C:\agent_work\5\s\src\Tools\Editor\WaveEngine.Runner\Viewers\BaseEditorScene.cs:line 101
at WaveEngine.Runner.Services.Commands.UpdateContainerHandler.ExecuteAsync(ICommandHandlerResult result, Boolean isRedo) in C:\agent_work\5\s\src\Tools\Editor\WaveEngine.Runner\Services\Commands\UpdateContainerHandler.cs:line 26
at WaveEngine.Runner.Services.UndoRedoService.Do(ICommandHandler handler, BaseEditorScene linkedScene) in C:\agent_work\5\s\src\Tools\Editor\WaveEngine.Runner\Services\UndoRedoService.cs:line 82
at WaveEngine.Runner.Services.Server.ViewCommandsService.BaseExecuteCommand(Command command, Object parameter, BaseEditorScene linkedScene) in C:\agent_work\5\s\src\Tools\Editor\WaveEngine.Runner\Services\Server\ViewCommandsService.cs:line 119
at WaveEngine.Runner.Services.Server.ViewsEditorServer.SendViewCommand(IAsyncStreamReader`1 requestStream, ServerCallContext context) in C:\agent_work\5\s\src\Tools\Editor\WaveEngine.Runner\Services\Server\ViewsEditorServer.cs:line 267

**Comment by jcant0n** [comment]
Hi Hromon,

Shadows are not available in the stable version right now, we are still working on it. 
But you can see how it goes here: https://twitter.com/jcant0n/status/1350156196163022848

It will be in the next public release in a few weeks.
Sorry for the inconvenience.

**Comment by Hromon** [comment]
Thanks for fast answer. I will wait)
And one more question, how use custom mesh maked in code?

P.S.
Sorry my english :D
